import { stub, type ParamDef } from '../ParameterRegistry';

export const architectureParams: ParamDef[] = [
  {
    id: 'architecture.density',
    label: 'Building Density',
    category: 'architecture',
    widget: 'slider',
    defaultValue: 0.55,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Likelihood that a roadside building slot is actually filled.',
    wired: true,
  },
  {
    id: 'architecture.spacing',
    label: 'Building Spacing',
    category: 'architecture',
    widget: 'slider',
    defaultValue: 22,
    min: 12,
    max: 50,
    step: 2,
    tooltip: 'Distance in meters between candidate building slots along a road.',
    wired: true,
  },
  {
    id: 'architecture.setback',
    label: 'Setback from Road',
    category: 'architecture',
    widget: 'slider',
    defaultValue: 10,
    min: 4,
    max: 30,
    step: 1,
    tooltip: 'How far back buildings sit from the road edge, in meters.',
    wired: true,
  },
  {
    id: 'architecture.minHeight',
    label: 'Min Height',
    category: 'architecture',
    widget: 'slider',
    defaultValue: 6,
    min: 3,
    max: 40,
    step: 1,
    tooltip: 'Shortest possible building height in meters.',
    wired: true,
  },
  {
    id: 'architecture.maxHeight',
    label: 'Max Height',
    category: 'architecture',
    widget: 'slider',
    defaultValue: 28,
    min: 6,
    max: 120,
    step: 2,
    tooltip: 'Tallest possible building height in meters.',
    wired: true,
  },
  stub('architecture.style', 'Architectural Style', 'architecture', 'mixed', 'select', {
    options: [
      { value: 'mixed', label: 'Mixed' },
      { value: 'modern', label: 'Modern' },
      { value: 'historic', label: 'Historic' },
      { value: 'industrial', label: 'Industrial' },
    ],
  }),
  stub('architecture.roofVariety', 'Roof Variety', 'architecture', 0.5, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('architecture.facadeDetail', 'Facade Detail', 'architecture', 0.5, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('architecture.windowDensity', 'Window Density', 'architecture', 0.5, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('architecture.colorPalette', 'Color Palette', 'architecture', 'neutral', 'select', {
    options: [
      { value: 'neutral', label: 'Neutral' },
      { value: 'warm', label: 'Warm' },
      { value: 'cool', label: 'Cool' },
    ],
  }),
  stub('architecture.courtyardChance', 'Courtyard Chance', 'architecture', 0.1, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('architecture.skyscraperChance', 'Skyscraper Chance', 'architecture', 0.05, 'slider', { min: 0, max: 1, step: 0.05 }),
];
