import { stub, type ParamDef } from '../ParameterRegistry';

export const gameplayParams: ParamDef[] = [
  {
    id: 'gameplay.chunkLoadRadius',
    label: 'Chunk Load Radius',
    category: 'gameplay',
    widget: 'slider',
    defaultValue: 2,
    min: 1,
    max: 5,
    step: 1,
    tooltip: 'How many chunks out from the player are streamed in. Higher sees further but costs more memory/CPU.',
    wired: true,
  },
  {
    id: 'gameplay.mouseSteeringSensitivity',
    label: 'Mouse Steering Sensitivity',
    category: 'gameplay',
    widget: 'slider',
    defaultValue: 0.0022,
    min: 0.0005,
    max: 0.01,
    step: 0.0005,
    tooltip: 'How much steering offset accumulates per pixel of mouse movement while mouse-steering is active.',
    wired: true,
  },
  {
    id: 'gameplay.mouseSteeringLinearity',
    label: 'Mouse Steering Linearity',
    category: 'gameplay',
    widget: 'slider',
    defaultValue: 1.6,
    min: 0.5,
    max: 4,
    step: 0.1,
    tooltip: 'Exponent applied to the steering offset — above 1 gives a gentle dead-zone near center with sharper response at the extremes.',
    wired: true,
  },
  {
    id: 'gameplay.unitsDisplay',
    label: 'Speed Units',
    category: 'gameplay',
    widget: 'select',
    defaultValue: 'kph',
    options: [
      { value: 'kph', label: 'km/h' },
      { value: 'mph', label: 'mph' },
    ],
    tooltip: 'Units the HUD speedometer displays.',
    wired: true,
  },
  {
    id: 'gameplay.restartOnFlip',
    label: 'Auto-Recover on Flip',
    category: 'gameplay',
    widget: 'toggle',
    defaultValue: true,
    tooltip: 'Automatically rights the car in place if it ends up upside down or on its side.',
    wired: true,
  },
  {
    id: 'gameplay.hudEnabled',
    label: 'Show HUD',
    category: 'gameplay',
    widget: 'toggle',
    defaultValue: true,
    tooltip: 'Toggles the speedometer/steering dial overlay.',
    wired: true,
  },
  stub('gameplay.collisionDamage', 'Collision Damage', 'gameplay', false, 'toggle', {
    tooltip: 'Reserved for a damage/health system; the chill design intentionally has no fail states yet.',
  }),
  stub('gameplay.fixedTimestepHz', 'Physics Rate (Hz)', 'gameplay', 60, 'slider', {
    min: 30,
    max: 120,
    step: 10,
    tooltip: 'Reserved for a tunable physics tick rate; needs accumulator/timestep rework to change live.',
  }),
];
