import { stub, type ParamDef } from '../ParameterRegistry';

export const lightingParams: ParamDef[] = [
  {
    id: 'lighting.sunIntensity',
    label: 'Sun Intensity',
    category: 'lighting',
    widget: 'slider',
    defaultValue: 2,
    min: 0,
    max: 5,
    step: 0.1,
    tooltip: 'Brightness of the directional sunlight.',
    wired: true,
  },
  {
    id: 'lighting.ambientIntensity',
    label: 'Ambient Intensity',
    category: 'lighting',
    widget: 'slider',
    defaultValue: 1.2,
    min: 0,
    max: 3,
    step: 0.1,
    tooltip: 'Brightness of the soft hemisphere sky/ground fill light.',
    wired: true,
  },
  {
    id: 'lighting.timeOfDay',
    label: 'Time of Day',
    category: 'lighting',
    widget: 'slider',
    defaultValue: 12,
    min: 0,
    max: 24,
    step: 0.5,
    tooltip: 'Hour of day, controlling sun elevation and sky tint.',
    wired: true,
  },
  {
    id: 'lighting.sunAzimuth',
    label: 'Sun Azimuth',
    category: 'lighting',
    widget: 'slider',
    defaultValue: 45,
    min: 0,
    max: 360,
    step: 5,
    tooltip: 'Compass direction the sun shines from, independent of time-of-day elevation.',
    wired: true,
  },
  {
    id: 'lighting.shadowQuality',
    label: 'Shadow Quality',
    category: 'lighting',
    widget: 'select',
    defaultValue: 'medium',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
    ],
    tooltip: 'Shadow map resolution; higher looks crisper but costs more GPU time.',
    wired: true,
  },
  {
    id: 'lighting.streetLightDensity',
    label: 'Street Light Density',
    category: 'lighting',
    widget: 'slider',
    defaultValue: 0.3,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely lamp posts are placed along roads (mirrors Street Furniture > Lamp Post Density).',
    wired: true,
  },
  {
    id: 'lighting.moonBrightness',
    label: 'Moon Brightness',
    category: 'lighting',
    widget: 'slider',
    defaultValue: 0.2,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Minimum ambient brightness floor at night, so the world is never pitch black.',
    wired: true,
  },
  {
    id: 'lighting.colorTemperature',
    label: 'Color Temperature',
    category: 'lighting',
    widget: 'slider',
    defaultValue: 5500,
    min: 2000,
    max: 9000,
    step: 100,
    tooltip: 'Tints the sunlight color from warm orange (low) to cool blue (high), in approximate Kelvin.',
    wired: true,
  },
  stub('lighting.bloom', 'Bloom', 'lighting', 0.2, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a bloom post-processing pass; needs a render-pass pipeline.',
  }),
];
