import { stub, type ParamDef } from '../ParameterRegistry';

export const roadParams: ParamDef[] = [
  {
    id: 'roads.seed',
    label: 'Road Seed',
    category: 'roads',
    widget: 'slider',
    defaultValue: 4242,
    min: 0,
    max: 9999,
    step: 1,
    tooltip: 'Changes the random seed for the road macro-grid, producing a different street layout.',
    wired: true,
  },
  {
    id: 'roads.macroCellSize',
    label: 'Macro Cell Size',
    category: 'roads',
    widget: 'slider',
    defaultValue: 320,
    min: 160,
    max: 640,
    step: 20,
    tooltip: 'Size in meters of the coarse grid that intersections are placed on — bigger means sparser, longer roads.',
    wired: true,
  },
  {
    id: 'roads.edgeProbability',
    label: 'Connection Density',
    category: 'roads',
    widget: 'slider',
    defaultValue: 0.65,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Likelihood that two neighboring intersections are connected by a road.',
    wired: true,
  },
  {
    id: 'roads.nodeJitter',
    label: 'Intersection Jitter',
    category: 'roads',
    widget: 'slider',
    defaultValue: 0.3,
    min: 0,
    max: 0.5,
    step: 0.05,
    tooltip: 'How far intersections can wander off their grid-cell center, as a fraction of cell size — adds organic curvature.',
    wired: true,
  },
  {
    id: 'roads.laneCount',
    label: 'Lane Count',
    category: 'roads',
    widget: 'slider',
    defaultValue: 2,
    min: 1,
    max: 4,
    step: 1,
    tooltip: 'Number of lane-divider markings painted across the road width.',
    wired: true,
  },
  {
    id: 'roads.width',
    label: 'Road Width',
    category: 'roads',
    widget: 'slider',
    defaultValue: 8,
    min: 4,
    max: 20,
    step: 1,
    tooltip: 'Width in meters of the flattened, dark-paved road surface.',
    wired: true,
  },
  {
    id: 'roads.shoulderWidth',
    label: 'Shoulder Width',
    category: 'roads',
    widget: 'slider',
    defaultValue: 1,
    min: 0,
    max: 4,
    step: 0.5,
    tooltip: 'How far beyond the paved edge the terrain ramps back up to its natural height.',
    wired: true,
  },
  {
    id: 'roads.markingsEnabled',
    label: 'Lane Markings',
    category: 'roads',
    widget: 'toggle',
    defaultValue: true,
    tooltip: 'Paints a centerline and lane-divider stripes on the road surface.',
    wired: true,
  },
  {
    id: 'roads.intersectionRadius',
    label: 'Intersection Radius',
    category: 'roads',
    widget: 'slider',
    defaultValue: 10,
    min: 4,
    max: 30,
    step: 1,
    tooltip: 'Extra flattening radius around intersections, so multiple roads meet without a height step.',
    wired: true,
  },
  stub('roads.curvatureStrictness', 'Curvature Strictness', 'roads', 0.5, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for curved (non-straight) road segments; needs a spline-based road geometry system.',
  }),
  stub('roads.highwayChance', 'Highway Chance', 'roads', 0.1, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a future elevated-highway road type; needs new road geometry.',
  }),
  stub('roads.bridgeChance', 'Bridge Chance', 'roads', 0.05, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a future bridge-over-terrain system; needs new road geometry.',
  }),
];
