import { stub, type ParamDef } from '../ParameterRegistry';

export const roadParams: ParamDef[] = [
  {
    id: 'roads.seed',
    label: 'Road Seed',
    category: 'roads',
    widget: 'slider',
    defaultValue: 4242,
    min: 0,
    max: 9999,
    step: 1,
    tooltip: 'Changes the random seed for the road macro-grid, producing a different street layout.',
    wired: true,
  },
  {
    id: 'roads.macroCellSize',
    label: 'Macro Cell Size',
    category: 'roads',
    widget: 'slider',
    defaultValue: 320,
    min: 160,
    max: 640,
    step: 20,
    tooltip: 'Size in meters of the coarse grid that intersections are placed on — bigger means sparser, longer roads.',
    wired: true,
  },
  {
    id: 'roads.edgeProbability',
    label: 'Connection Density',
    category: 'roads',
    widget: 'slider',
    defaultValue: 0.65,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Likelihood that two neighboring intersections are connected by a road.',
    wired: true,
  },
  {
    id: 'roads.nodeJitter',
    label: 'Intersection Jitter',
    category: 'roads',
    widget: 'slider',
    defaultValue: 0.3,
    min: 0,
    max: 0.5,
    step: 0.05,
    tooltip: 'How far intersections can wander off their grid-cell center, as a fraction of cell size — adds organic curvature.',
    wired: true,
  },
  stub('roads.laneCount', 'Lane Count', 'roads', 2, 'slider', { min: 1, max: 4, step: 1 }),
  stub('roads.curvatureStrictness', 'Curvature Strictness', 'roads', 0.5, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('roads.width', 'Road Width', 'roads', 8, 'slider', { min: 4, max: 20, step: 1 }),
  stub('roads.shoulderWidth', 'Shoulder Width', 'roads', 1, 'slider', { min: 0, max: 4, step: 0.5 }),
  stub('roads.markingsEnabled', 'Lane Markings', 'roads', true, 'toggle'),
  stub('roads.intersectionRadius', 'Intersection Radius', 'roads', 10, 'slider', { min: 4, max: 30, step: 1 }),
  stub('roads.highwayChance', 'Highway Chance', 'roads', 0.1, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('roads.bridgeChance', 'Bridge Chance', 'roads', 0.05, 'slider', { min: 0, max: 1, step: 0.05 }),
];
