import type { ParamDef } from '../ParameterRegistry';

export const streetFurnitureParams: ParamDef[] = [
  {
    id: 'streetFurniture.signsEnabled',
    label: 'Intersection Signs',
    category: 'streetFurniture',
    widget: 'toggle',
    defaultValue: true,
    tooltip: 'Whether cosmetic sign posts are placed at road intersections.',
    wired: true,
  },
  {
    id: 'streetFurniture.lampPostDensity',
    label: 'Lamp Post Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.4,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely lamp posts are placed along roadsides.',
    wired: true,
  },
  {
    id: 'streetFurniture.benchDensity',
    label: 'Bench Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.1,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely benches are placed along roadsides.',
    wired: true,
  },
  {
    id: 'streetFurniture.trashCanDensity',
    label: 'Trash Can Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.1,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely trash cans are placed along roadsides.',
    wired: true,
  },
  {
    id: 'streetFurniture.fireHydrantDensity',
    label: 'Fire Hydrant Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.05,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely fire hydrants are placed along roadsides.',
    wired: true,
  },
  {
    id: 'streetFurniture.busStopChance',
    label: 'Bus Stop Chance',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.05,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How often a roadside slot gets a bus-stop shelter.',
    wired: true,
  },
  {
    id: 'streetFurniture.billboardChance',
    label: 'Billboard Chance',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.03,
    min: 0,
    max: 1,
    step: 0.01,
    tooltip: 'How often a roadside slot gets a raised billboard panel.',
    wired: true,
  },
  {
    id: 'streetFurniture.fenceDensity',
    label: 'Fence Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.1,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely short fence sections are placed along roadsides.',
    wired: true,
  },
];
