import { stub, type ParamDef } from '../ParameterRegistry';

export const streetFurnitureParams: ParamDef[] = [
  {
    id: 'streetFurniture.signsEnabled',
    label: 'Intersection Signs',
    category: 'streetFurniture',
    widget: 'toggle',
    defaultValue: true,
    tooltip: 'Whether cosmetic sign posts are placed at road intersections.',
    wired: true,
  },
  {
    id: 'streetFurniture.lampPostDensity',
    label: 'Lamp Post Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.4,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely lamp posts are placed along roadsides.',
    wired: true,
  },
  {
    id: 'streetFurniture.benchDensity',
    label: 'Bench Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.1,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely benches are placed along roadsides.',
    wired: true,
  },
  {
    id: 'streetFurniture.trashCanDensity',
    label: 'Trash Can Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.1,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely trash cans are placed along roadsides.',
    wired: true,
  },
  {
    id: 'streetFurniture.fireHydrantDensity',
    label: 'Fire Hydrant Density',
    category: 'streetFurniture',
    widget: 'slider',
    defaultValue: 0.05,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely fire hydrants are placed along roadsides.',
    wired: true,
  },
  stub('streetFurniture.busStopChance', 'Bus Stop Chance', 'streetFurniture', 0.05, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for bus stop props; needs a new placement/mesh.',
  }),
  stub('streetFurniture.billboardChance', 'Billboard Chance', 'streetFurniture', 0.03, 'slider', {
    min: 0,
    max: 1,
    step: 0.01,
    tooltip: 'Reserved for billboard props; needs a new placement/mesh.',
  }),
  stub('streetFurniture.fenceDensity', 'Fence Density', 'streetFurniture', 0.1, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for fence placement along property lines; needs a new placement system.',
  }),
];
