import { stub, type ParamDef } from '../ParameterRegistry';

export const terrainParams: ParamDef[] = [
  {
    id: 'terrain.seed',
    label: 'Terrain Seed',
    category: 'terrain',
    widget: 'slider',
    defaultValue: 1337,
    min: 0,
    max: 9999,
    step: 1,
    tooltip: 'Changes the random seed for terrain noise, producing a different landscape.',
    wired: true,
  },
  {
    id: 'terrain.baseFrequency',
    label: 'Base Frequency',
    category: 'terrain',
    widget: 'slider',
    defaultValue: 0.004,
    min: 0.001,
    max: 0.02,
    step: 0.0005,
    tooltip: 'Controls how rapidly terrain height varies across distance — higher is bumpier hills closer together.',
    wired: true,
  },
  {
    id: 'terrain.octaves',
    label: 'Octaves',
    category: 'terrain',
    widget: 'slider',
    defaultValue: 3,
    min: 1,
    max: 6,
    step: 1,
    tooltip: 'Number of noise layers combined for terrain detail. More octaves add finer bumps on top of the base shape.',
    wired: true,
  },
  {
    id: 'terrain.persistence',
    label: 'Persistence',
    category: 'terrain',
    widget: 'slider',
    defaultValue: 0.4,
    min: 0.1,
    max: 0.9,
    step: 0.05,
    tooltip: 'How much each finer noise octave contributes relative to the previous one.',
    wired: true,
  },
  {
    id: 'terrain.amplitude',
    label: 'Amplitude',
    category: 'terrain',
    widget: 'slider',
    defaultValue: 4,
    min: 0,
    max: 15,
    step: 0.5,
    tooltip: 'Overall vertical scale of the terrain in meters. Higher values make hills taller and slopes steeper.',
    wired: true,
  },
  stub('terrain.lacunarity', 'Lacunarity', 'terrain', 2, 'slider', { min: 1.5, max: 3, step: 0.1 }),
  stub('terrain.erosion', 'Erosion Strength', 'terrain', 0, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('terrain.riverDensity', 'River Density', 'terrain', 0, 'slider', { min: 0, max: 1, step: 0.05 }),
  stub('terrain.plateauBias', 'Plateau Bias', 'terrain', 0, 'slider', { min: -1, max: 1, step: 0.05 }),
  stub('terrain.coastalFlattening', 'Coastal Flattening', 'terrain', 0, 'toggle'),
  stub('terrain.biomeBlend', 'Biome Blend Width', 'terrain', 40, 'slider', { min: 0, max: 200, step: 5 }),
  stub('terrain.rockiness', 'Rockiness', 'terrain', 0.2, 'slider', { min: 0, max: 1, step: 0.05 }),
];
