import { stub, type ParamDef } from '../ParameterRegistry';

export const vegetationParams: ParamDef[] = [
  {
    id: 'vegetation.density',
    label: 'Tree Density',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 0.3,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Likelihood a candidate grid cell grows a tree, after road/building/slope rejection.',
    wired: true,
  },
  {
    id: 'vegetation.cellSize',
    label: 'Tree Grid Spacing',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 7,
    min: 3,
    max: 20,
    step: 1,
    tooltip: 'Base spacing in meters of the candidate grid trees are sampled from — smaller means a denser canopy.',
    wired: true,
  },
  {
    id: 'vegetation.minHeight',
    label: 'Min Tree Height',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 4,
    min: 2,
    max: 15,
    step: 0.5,
    tooltip: 'Shortest possible tree height in meters.',
    wired: true,
  },
  {
    id: 'vegetation.maxHeight',
    label: 'Max Tree Height',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 9,
    min: 3,
    max: 25,
    step: 0.5,
    tooltip: 'Tallest possible tree height in meters.',
    wired: true,
  },
  {
    id: 'vegetation.seasonalTint',
    label: 'Seasonal Tint',
    category: 'vegetation',
    widget: 'select',
    defaultValue: 'summer',
    options: [
      { value: 'spring', label: 'Spring' },
      { value: 'summer', label: 'Summer' },
      { value: 'autumn', label: 'Autumn' },
      { value: 'winter', label: 'Winter' },
    ],
    tooltip: 'Tints tree canopy color to match the season.',
    wired: true,
  },
  stub('vegetation.biomeType', 'Biome Type', 'vegetation', 'temperate', 'select', {
    options: [
      { value: 'temperate', label: 'Temperate' },
      { value: 'arid', label: 'Arid' },
      { value: 'tropical', label: 'Tropical' },
      { value: 'alpine', label: 'Alpine' },
    ],
    tooltip: 'Reserved for biome-specific vegetation meshes; needs new tree/shrub variants.',
  }),
  stub('vegetation.canopyShape', 'Canopy Shape', 'vegetation', 'conical', 'select', {
    options: [
      { value: 'conical', label: 'Conical' },
      { value: 'round', label: 'Round' },
      { value: 'sparse', label: 'Sparse' },
    ],
    tooltip: 'Reserved for alternate canopy geometry; needs new tree mesh variants.',
  }),
  stub('vegetation.grassDensity', 'Grass Density', 'vegetation', 0.5, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a ground-cover grass system; needs new placement/rendering.',
  }),
  stub('vegetation.shrubDensity', 'Shrub Density', 'vegetation', 0.2, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a shrub placement system; needs new placement/rendering.',
  }),
  stub('vegetation.flowerChance', 'Flower Chance', 'vegetation', 0.05, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a flower placement system; needs new placement/rendering.',
  }),
  stub('vegetation.windSway', 'Wind Sway', 'vegetation', 0.2, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for animated tree sway; needs a per-frame vegetation animation system.',
  }),
];
