import { stub, type ParamDef } from '../ParameterRegistry';

export const vegetationParams: ParamDef[] = [
  {
    id: 'vegetation.density',
    label: 'Tree Density',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 0.3,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Likelihood a candidate grid cell grows a tree, after road/building/slope rejection.',
    wired: true,
  },
  {
    id: 'vegetation.cellSize',
    label: 'Tree Grid Spacing',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 7,
    min: 3,
    max: 20,
    step: 1,
    tooltip: 'Base spacing in meters of the candidate grid trees are sampled from — smaller means a denser canopy.',
    wired: true,
  },
  {
    id: 'vegetation.minHeight',
    label: 'Min Tree Height',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 4,
    min: 2,
    max: 15,
    step: 0.5,
    tooltip: 'Shortest possible tree height in meters.',
    wired: true,
  },
  {
    id: 'vegetation.maxHeight',
    label: 'Max Tree Height',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 9,
    min: 3,
    max: 25,
    step: 0.5,
    tooltip: 'Tallest possible tree height in meters.',
    wired: true,
  },
  {
    id: 'vegetation.seasonalTint',
    label: 'Seasonal Tint',
    category: 'vegetation',
    widget: 'select',
    defaultValue: 'summer',
    options: [
      { value: 'spring', label: 'Spring' },
      { value: 'summer', label: 'Summer' },
      { value: 'autumn', label: 'Autumn' },
      { value: 'winter', label: 'Winter' },
    ],
    tooltip: 'Tints tree canopy color to match the season.',
    wired: true,
  },
  {
    id: 'vegetation.biomeType',
    label: 'Biome Type',
    category: 'vegetation',
    widget: 'select',
    defaultValue: 'temperate',
    options: [
      { value: 'temperate', label: 'Temperate' },
      { value: 'arid', label: 'Arid' },
      { value: 'tropical', label: 'Tropical' },
      { value: 'alpine', label: 'Alpine' },
    ],
    tooltip: 'Shifts canopy color and overall tree density toward a biome character (arid is sparse and olive, tropical is dense and vivid, alpine is sparse and muted).',
    wired: true,
  },
  {
    id: 'vegetation.canopyShape',
    label: 'Canopy Shape',
    category: 'vegetation',
    widget: 'select',
    defaultValue: 'conical',
    options: [
      { value: 'conical', label: 'Conical' },
      { value: 'round', label: 'Round' },
      { value: 'sparse', label: 'Sparse' },
    ],
    tooltip: 'Geometry of tree canopies: pointed conifer cones, rounded deciduous crowns, or thinner sparse cones.',
    wired: true,
  },
  {
    id: 'vegetation.grassDensity',
    label: 'Grass Density',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely small grass tufts are scattered across open ground.',
    wired: true,
  },
  {
    id: 'vegetation.shrubDensity',
    label: 'Shrub Density',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 0.2,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'How densely small bushes are scattered across open ground.',
    wired: true,
  },
  {
    id: 'vegetation.flowerChance',
    label: 'Flower Chance',
    category: 'vegetation',
    widget: 'slider',
    defaultValue: 0.05,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Chance an open-ground spot grows a small colored flower instead of grass or shrub.',
    wired: true,
  },
  stub('vegetation.windSway', 'Wind Sway', 'vegetation', 0.2, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for animated tree sway; needs a per-frame vegetation animation system.',
  }),
];
