import type { ParamDef } from '../ParameterRegistry';

export const vehicleParams: ParamDef[] = [
  {
    id: 'vehicle.maxSteerAngleDeg',
    label: 'Max Steering Angle',
    category: 'vehicle',
    widget: 'slider',
    defaultValue: 31.5,
    min: 10,
    max: 45,
    step: 1,
    tooltip: 'Maximum angle in degrees the front wheels can turn to, in either direction.',
    wired: true,
  },
  {
    id: 'vehicle.maxEngineForce',
    label: 'Engine Power',
    category: 'vehicle',
    widget: 'slider',
    defaultValue: 3000,
    min: 1000,
    max: 8000,
    step: 100,
    tooltip: 'Maximum forward/reverse force the engine can apply to the rear wheels.',
    wired: true,
  },
  {
    id: 'vehicle.maxBrakeForce',
    label: 'Brake Force',
    category: 'vehicle',
    widget: 'slider',
    defaultValue: 60,
    min: 10,
    max: 200,
    step: 5,
    tooltip: 'Maximum braking force applied to all four wheels.',
    wired: true,
  },
  {
    id: 'vehicle.suspensionStiffness',
    label: 'Suspension Stiffness',
    category: 'vehicle',
    widget: 'slider',
    defaultValue: 28,
    min: 5,
    max: 60,
    step: 1,
    tooltip: 'Spring stiffness of the wheel suspension; higher feels stiffer and less bouncy.',
    wired: true,
  },
  {
    id: 'vehicle.chassisMass',
    label: 'Chassis Mass (kg)',
    category: 'vehicle',
    widget: 'slider',
    defaultValue: 1200,
    min: 600,
    max: 2500,
    step: 50,
    tooltip: 'Mass of the car body; heavier cars accelerate/brake more slowly but feel more stable.',
    wired: true,
  },
];
