import { stub, type ParamDef } from '../ParameterRegistry';

export const weatherParams: ParamDef[] = [
  {
    id: 'weather.fogNear',
    label: 'Fog Near Distance',
    category: 'weather',
    widget: 'slider',
    defaultValue: 60,
    min: 10,
    max: 200,
    step: 5,
    tooltip: 'Distance in meters where fog begins to appear.',
    wired: true,
  },
  {
    id: 'weather.fogFar',
    label: 'Fog Far Distance',
    category: 'weather',
    widget: 'slider',
    defaultValue: 220,
    min: 50,
    max: 600,
    step: 10,
    tooltip: 'Distance in meters where fog becomes fully opaque.',
    wired: true,
  },
  {
    id: 'weather.fogColorWarmth',
    label: 'Fog Color Warmth',
    category: 'weather',
    widget: 'slider',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Shifts fog color from cool blue-grey toward a warm haze tint.',
    wired: true,
  },
  stub('weather.cloudCover', 'Cloud Cover', 'weather', 0.3, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a sky/cloud rendering system; needs a sky dome or cloud shader.',
  }),
  stub('weather.precipitation', 'Precipitation', 'weather', 'none', 'select', {
    options: [
      { value: 'none', label: 'None' },
      { value: 'rain', label: 'Rain' },
      { value: 'snow', label: 'Snow' },
    ],
    tooltip: 'Reserved for rain/snow particle effects; needs a new particle system.',
  }),
  stub('weather.windSpeed', 'Wind Speed', 'weather', 3, 'slider', {
    min: 0,
    max: 30,
    step: 1,
    tooltip: 'Reserved for animated tree sway; needs a per-frame vegetation animation system.',
  }),
  stub('weather.humidity', 'Humidity', 'weather', 0.5, 'slider', {
    min: 0,
    max: 1,
    step: 0.05,
    tooltip: 'Reserved for a haze/atmosphere shader; not yet wired.',
  }),
  stub('weather.stormChance', 'Storm Chance', 'weather', 0.02, 'slider', {
    min: 0,
    max: 1,
    step: 0.01,
    tooltip: 'Reserved for dynamic storm events; needs a weather-event system.',
  }),
  stub('weather.rainbowChance', 'Rainbow Chance', 'weather', 0.01, 'slider', {
    min: 0,
    max: 1,
    step: 0.01,
    tooltip: 'Reserved for a rainbow visual effect; not yet wired.',
  }),
];
